// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2bcKf7rhKEepTKtcHO4OaHPy0X-_CLUc',
    appId: '1:150107637704:web:583ac466f5113703dfe2fd',
    messagingSenderId: '150107637704',
    projectId: 'social-app-8a979',
    authDomain: 'social-app-8a979.firebaseapp.com',
    storageBucket: 'social-app-8a979.appspot.com',
    measurementId: 'G-TMDWWMYD6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4gQnUr7T-ugudqQC8z9UYwD_QsZLoAM0',
    appId: '1:150107637704:android:911520708cf4e3d1dfe2fd',
    messagingSenderId: '150107637704',
    projectId: 'social-app-8a979',
    storageBucket: 'social-app-8a979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB05LLDsEiiRUfZw8Sfn0r3kBVZhECN6sU',
    appId: '1:150107637704:ios:7a89833f56c5256bdfe2fd',
    messagingSenderId: '150107637704',
    projectId: 'social-app-8a979',
    storageBucket: 'social-app-8a979.appspot.com',
    androidClientId: '150107637704-ve8o4bk1oac6lvauam566jgogbv83vt2.apps.googleusercontent.com',
    iosClientId: '150107637704-o1a02mi9336a6d2tev36hbk4m0hkmtqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB05LLDsEiiRUfZw8Sfn0r3kBVZhECN6sU',
    appId: '1:150107637704:ios:7a89833f56c5256bdfe2fd',
    messagingSenderId: '150107637704',
    projectId: 'social-app-8a979',
    storageBucket: 'social-app-8a979.appspot.com',
    androidClientId: '150107637704-ve8o4bk1oac6lvauam566jgogbv83vt2.apps.googleusercontent.com',
    iosClientId: '150107637704-o1a02mi9336a6d2tev36hbk4m0hkmtqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
